[package]
name = "bevy-mesh-text-3d"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = "0.16.1"
cosmic-text = { version = "0.14.2", features = ["wasm-web"] }
lyon = "1.0.1" 
thiserror = "2.0.12"
